site_name: 155YGIS
nav:
  - 155YGIS – charakteristika: index.md
  - Cvičení:
      - Úvod do práce v prostředí ArcGIS, prostorová data, datové zdroje, atributová tabulka: cviceni/cviceni1.md
      - Vektorová data, atributové dotazy, prostorové dotazy: cviceni/cviceni2.md
      - Prostorové funkce (geoprocessing), spatial join: cviceni/cviceni4.md
      - Souřadnicové referenční systémy v ČR | přehled typů dat a zdrojů, webové mapové služby | připojení externích dat: cviceni/cviceni3.md
  - Semestrální práce: semestralka.md
  - Datové zdroje: data.md
  # - Výuková videa: videa.md

  # - Kvíz: quiz.md
plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.png
  logo: assets/favicon.svg
  icon:
    annotation: material/plus-circle
  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
  language: cs
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: custom
      accent: custom
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: custom
      accent: custom
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CTUGeomatics
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/geomatics.ctu
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/geomatics.ctu
copyright: <a href="https://geomatics.fsv.cvut.cz" target="_blank">Katedra geomatiky</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;2023-2024
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.tilde

